---
- name: Update /etc/hosts file
  hosts: all
  become: true  
  tasks:
    - name: Add host information to /etc/hosts
      lineinfile:
        path: /etc/hosts
        line: "{{ hostvars[item]['ansible_default_ipv4']['address'] }} {{ item }}"
      loop: "{{ groups['all'] }}"
      when: item in hosts
