---
- name: Check connectivity between nosts in the "{{ group }}" DNS
  hosts: "{{ group }}"
  gather_facts: false
  tasks:
    - name: Register ping result
      command: ping -c 1 "{{ item }}"
      failed_when:
        - router_ping.rc != 0
      register: router_ping
      changed_when: false
      with_items: "{{ groups[group] }}"
      ignore_errors: yes

    - name: set stats
      set_stats:
        data:
          "{{ inventory_hostname }}": "{{ item }}"
      when: item.failed
      loop: "{{ router_ping.results }}"
      loop_control:
        label: "{{ item.item }}"
        
    - name: Show failures
      debug:
        msg: "{{ inventory_hostname }} can't ping {{ item.item }}"
      when: item.failed
      loop: "{{ router_ping.results }}"
      loop_control:
        label: "{{ item.item }}"
      failed_when: item.failed
