---
- name: Check connectivity between nosts in the "{{ group }}" DNS
  hosts: "{{ group }}"
  gather_facts: false
  tasks:
    - include_tasks: ping_hosts.yml
      


    #- name: set stats
    #  set_stats:
    #    data:
   #       broken: "{{ item.item }}"
    #  when: item.failed
    #  loop: "{{ router_ping.results }}"
    #  loop_control:
    #    label: "{{ item.item }}"
        
    #- name: Show failures
   #   debug:
    #    msg: "{{ inventory_hostname }} can't ping {{ item.item }}"
   #   when: item.failed
   #   loop: "{{ router_ping.results }}"
  #    loop_control:
  #      label: "{{ item.item }}"
  #    failed_when: item.failed
