---
- name: Remove from /etc/hosts file for demo
  hosts: all
  become: true  
  tasks:
    - name: Add host information to /etc/hosts
      lineinfile:
        path: /etc/hosts
        regexp: "{{ hostvars[item]['ansible_default_ipv4']['address'] }} {{ item }}"
        state: absent
      loop: "{{ groups['all'] }}"
      when: inventory_hostname is host
